export const IpcChannels = {
  SESSION_START: 'session:start',
  SESSION_STOP: 'session:stop',
  SESSION_PAUSED: 'session:paused',
  SESSION_RESUMED: 'session:resumed',
  TOKENS_FINAL: 'tokens:final',
  TOKENS_NONFINAL: 'tokens:nonfinal',
  SESSION_STATUS: 'session:status',
  SESSION_TEXT: 'session:text',
  SESSION_REQUEST_PAUSE: 'session:request-pause',
  SESSION_REQUEST_RESUME: 'session:request-resume',
  SETTINGS_GET: 'settings:get',
  SETTINGS_SET: 'settings:set',
  SETTINGS_UPDATED: 'settings:updated',
  WINDOW_HIDE: 'window:hide',
  WINDOW_ESCAPE_HIDE: 'window:escape-hide',
  AUDIO_GET_DEVICES: 'audio:get-devices',
  THEME_GET: 'theme:get',
  THEME_RESOLVED: 'theme:resolved',
  SESSION_ERROR: 'session:error',
  SESSION_OPEN_SETTINGS: 'session:open-settings',
  SESSION_OPEN_MIC_SETTINGS: 'session:open-mic-settings',
  SESSION_DISMISS_ERROR: 'session:dismiss-error',
  LOG_PATH_GET: 'log:get-path',
  LOG_REVEAL: 'log:reveal',
  LOG_FROM_RENDERER: 'log:from-renderer',
} as const;
